apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: YOUR_ECR_IMAGE_URL
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "ap-south-1"
